name = "NamedVectorizations"
uuid = "93c25245-795c-4f39-9b17-d28542eb77a0"
authors = ["Nicola Mignoni"]
version = "0.1.0"

[compat]
Test = "1.11.0"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
